#
# bash_aliases
#

alias reload='. $HOME/.bash_profile'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias cdhist="dirs -v"

alias cl='clear'
alias cla='clear;la'
alias cll='clear;ll'
alias cls='clear;ls'
alias clal='clear;lal'
alias rmdir='rm -rf'
alias d='date +%Y%m%d-%H%M%S'
alias h='history'
alias ls='ls -F --color=auto'
alias l='ls'
alias la='ls -a'
alias ll='ls -ltr'
alias lu='ls -ltur'
alias lal='ls -altr'
alias ldir='ll -d */'
alias sl='ls'
alias less='less -iMFR'
alias more='less'
alias mroe='more'
alias m='more'
alias r='fc -s'
alias igrep='grep -i'
alias rgrep='grep -r'
alias ftail='tail -f'
alias hn='hostname -a'
alias va='vi ~/.bash/.bash_aliases; source ~/.bash/.bash_aliases && echo "aliases sourced"'
alias vi='vim'

# coloured output using grc
alias ping='grc ping'
alias netstat='grc netstat'
alias traceroute='grc traceroute'
alias diff='grc diff'
alias tail='grc tail'
alias ps='grc ps'
alias lsof='grc lsof'


# autosys handy aliases. All start with "job".
alias jobls='autorep -J'
alias jobll='autorep -q -J'
alias jobstart='sendevent -E FORCE_STARTJOB -J'
alias jobhold='sendevent -E JOB_ON_HOLD -J'
alias jobice='sendevent -E JOB_ON_ICE -J'
alias jobkill='sendevent -E KILLJOB -J'
alias joboffhold='sendevent -E JOB_OFF_HOLD -J'
alias joboffice='sendevent -E JOB_OFF_ICE -J'
alias jobhist='jobrunhist -j'
alias jobdepends='job_depends -c -J'
alias jobsu='sendevent -E CHANGE_STATUS -s SUCCESS -J'
alias jobterm='sendevent -E CHANGE_STATUS -s TERMINATED -J'

alias scp='scp -o StrictHostKeyChecking=no -c arcfour -o Compression=no'
alias fullps='ps -auxwww'
alias functions='declare -F'
alias xml='xmllint --format'
